from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

from dotenv import load_dotenv


ROOT_DIR = Path(__file__).resolve().parent
SRC_DIR = ROOT_DIR / "src"
sys.path.insert(0, str(SRC_DIR))

from utils.config import load_json_config, get_data_path
from db.sqlite import connect, init_db, ensure_source_table


# =========================
# CONFIG (edit these)
# =========================
SOURCE_NAME = "example_source"  # e.g., "imdb_movies"
ITEM_TYPE = "example_type"  # e.g., "movie"
SEED_URLS = ["https://example.com/seed"]
ENABLED = True

# Optional: override class name or module file name
CLASS_NAME = None  # e.g., "ImdbCrawler"
MODULE_NAME = None  # e.g., "imdb"
# =========================


def _setup_logging(level: str) -> None:
    logging.basicConfig(
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s | %(levelname)s | %(message)s",
    )


def _derive_module_name(source_name: str) -> str:
    return source_name.replace("-", "_").lower()


def _derive_class_name(source_name: str) -> str:
    parts = source_name.replace("-", "_").split("_")
    return "".join(p.capitalize() for p in parts) + "Crawler"


def _crawler_file_path(module_name: str) -> Path:
    return SRC_DIR / "crawlers" / f"{module_name}.py"


def _crawler_dotted_path(module_name: str, class_name: str) -> str:
    return f"crawlers.{module_name}.{class_name}"


def _load_sources(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_sources(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _add_source_entry(sources_path: Path, entry: dict) -> None:
    data = _load_sources(sources_path)
    sources = data.get("sources", [])
    if any(s.get("name") == entry["name"] for s in sources):
        raise ValueError(f"Source already exists: {entry['name']}")
    sources.append(entry)
    data["sources"] = sources
    _write_sources(sources_path, data)


def _remove_source_entry(sources_path: Path, source_name: str) -> bool:
    data = _load_sources(sources_path)
    sources = data.get("sources", [])
    new_sources = [s for s in sources if s.get("name") != source_name]
    if len(new_sources) == len(sources):
        return False
    data["sources"] = new_sources
    _write_sources(sources_path, data)
    return True


def _write_crawler_stub(module_name: str, class_name: str) -> None:
    path = _crawler_file_path(module_name)
    if path.exists():
        raise FileExistsError(f"Crawler file already exists: {path}")
    path.write_text(
        (
            '"""Crawler stub."""\n'
            "from __future__ import annotations\n\n"
            "from typing import Iterable\n\n"
            "from crawlers.base import BaseCrawler, CrawlItem\n\n\n"
            f"class {class_name}(BaseCrawler):\n"
            "    def run(self) -> Iterable[CrawlItem]:\n"
            "        return self.stub_run()\n"
        ),
        encoding="utf-8",
    )


def _delete_crawler_stub(module_name: str) -> bool:
    path = _crawler_file_path(module_name)
    if not path.exists():
        return False
    path.unlink()
    return True


def main(source_name: str) -> None:
    load_dotenv()
    app_cfg = load_json_config("app.json")
    _setup_logging(app_cfg["app"]["log_level"])

    sources_path = ROOT_DIR / "config" / "sources.json"
    module_name = MODULE_NAME or _derive_module_name(source_name)
    class_name = CLASS_NAME or _derive_class_name(source_name)

    _write_crawler_stub(module_name, class_name)
    entry = {
        "name": source_name,
        "enabled": ENABLED,
        "item_type": ITEM_TYPE,
        "crawler": _crawler_dotted_path(module_name, class_name),
        "seed_urls": SEED_URLS,
        "notes": "Auto-generated by add_crawler.py",
    }
    _add_source_entry(sources_path, entry)

    db_path = get_data_path(app_cfg["database"]["path"])
    conn = connect(db_path)
    init_db(conn)
    ensure_source_table(conn, source_name)
    conn.close()

    logging.info("Added crawler: %s", source_name)
    logging.info("Module: %s | Class: %s", module_name, class_name)
    logging.info("Updated: %s", sources_path)


if __name__ == "__main__":
    main(SOURCE_NAME)
