"""Demo data for _canadian_jobbank — real rows from the live site."""

DEMO_DATA = [
    ['CareerBeacon', 'software development manager', 'March 12, 2026', 'RBC Dominion Securities', 'Location', 'Toronto (ON)', 'Salary\n\t\t\t\t\t\t$43.75 to $103.37 hourly', 'Job number:', '2194265', 'software development manager - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/reg/instructions', '/jobsearch/jobposting/49094043?source=searchresults', '#favourite-popup-49094043'],
    ['On site', 'Direct Apply', 'Posted on Job Bank', 'This job was posted directly by the employer on Job Bank.', 'Job Bank', 'records office supervisor', 'January 08, 2026', 'Gold Star Wholesale Furniture Ltd.', 'Location', 'Edmonton (AB)', 'Salary\n\t\t\t\t\t\t$36.00 hourly', 'Job number:', '3479798', 'records office supervisor - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '#favourite-popup-49113545', '/reg/instructions', '/login', '/jobsearch/jobposting/49113545?source=searchresults'],
    ['On site', 'Direct Apply', 'Posted on Job Bank', 'This job was posted directly by the employer on Job Bank.', 'Job Bank', 'administrative clerks supervisor', 'March 10, 2026', 'Save On Lens', 'Location', 'Richmond (BC)', 'Salary\n\t\t\t\t\t\t$37.00 hourly', 'Job number:', '3525374', 'administrative clerks supervisor - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/jobsearch/jobposting/49079587?source=searchresults', '/reg/instructions', '/login', '#favourite-popup-49079587'],
    ['CareerBeacon', 'manager, computer applications', 'March 08, 2026', 'RBC Dominion Securities', 'Location', 'Toronto (ON)', 'Salary\n\t\t\t\t\t\t$43.75 to $103.37 hourly', 'Job number:', '2210533', 'manager, computer applications - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/reg/instructions', '#favourite-popup-49065787', '/jobsearch/jobposting/49065787?source=searchresults'],
    ['New', 'CareerBeacon', 'data scientist', 'March 15, 2026', 'RBC Dominion Securities', 'Location', 'Toronto (ON)', 'Salary\n\t\t\t\t\t\t$30.00 to $69.74 hourly', 'Job number:', '2206786', 'data scientist - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/reg/instructions', '/jobsearch/jobposting/49111567?source=searchresults', '#favourite-popup-49111567'],
    ['New', 'Remote', 'Direct Apply', 'Posted on Job Bank', 'This job was posted directly by the employer on Job Bank.', 'Job Bank', 'data scientist', 'March 20, 2026', 'PRA Group Canada Inc.', 'Location', 'London, ON', 'Salary\n\t\t\t\t\t\t$85,000.00 to $95,000.00 annually (to be negotiated)', 'Job number:', '3523745', 'data scientist - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/reg/instructions', '#favourite-popup-49143239', '/jobsearch/jobposting/49143239?source=searchresults'],
    ['On site', 'Direct Apply', 'Posted on Job Bank', 'This job was posted directly by the employer on Job Bank.', 'Job Bank', 'records office supervisor', 'January 13, 2026', 'BSG Carrier', 'Location', 'Edmonton (AB)', 'Salary\n\t\t\t\t\t\t$36.00 hourly', 'Job number:', '3483950', 'records office supervisor - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/reg/instructions', '#favourite-popup-49137661', '/jobsearch/jobposting/49137661?source=searchresults'],
    ['Jobillico', 'software development manager', 'March 14, 2026', 'Fed IT', 'Location', 'Sainte-Julie (QC)', 'Salary\n\t\t\t\t\t\t$90,000.00 to $120,000.00 annually', 'Job number:', '16887432', 'software development manager - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/jobsearch/jobposting/49107349?source=searchresults', '/reg/instructions', '#favourite-popup-49107349'],
    ['On site', 'Direct Apply', 'Posted on Job Bank', 'This job was posted directly by the employer on Job Bank.', 'Job Bank', 'operations supervisor', 'November 21, 2025', 'Hotel Le Germain Quebec', 'Location', 'Quebec (QC)', 'Salary\n\t\t\t\t\t\t$55,000.00 to $57,000.00 annually (to be negotiated)', 'Job number:', '3449558', 'operations supervisor - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/jobsearch/jobposting/49122305?source=searchresults', '#favourite-popup-49122305', '/reg/instructions'],
    ['indeed.com', 'cloud services manager', 'March 11, 2026', 'Global Convention Services', 'Location', 'Saint John (NB)', 'Salary\n\t\t\t\t\t\t$65,000.00 to $75,000.00 annually', 'Job number:', '10062429447', 'cloud services manager - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '#favourite-popup-49087128', '/jobsearch/jobposting/49087128?source=searchresults', '/reg/instructions'],
    ['CareerBeacon', 'data mining analyst', 'March 10, 2026', 'RBC Dominion Securities', 'Location', 'Toronto (ON)', 'Salary\n\t\t\t\t\t\t$30.00 to $69.74 hourly', 'Job number:', '2203155', 'data mining analyst - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/jobsearch/jobposting/49079409?source=searchresults', '#favourite-popup-49079409', '/reg/instructions'],
    ['On site', 'Direct Apply', 'Posted on Job Bank', 'This job was posted directly by the employer on Job Bank.', 'Job Bank', 'database analyst', 'March 02, 2026', 'White Cap Supply Canada Inc.', 'Location', 'Dartmouth (NS)', 'Salary\n\t\t\t\t\t\t$33.65 hourly', 'Job number:', '3519588', 'database analyst - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '#favourite-popup-49030137', '/jobsearch/jobposting/49030137?source=searchresults', '/reg/instructions'],
    ['On site', 'Direct Apply', 'Posted on Job Bank', 'This job was posted directly by the employer on Job Bank.', 'Job Bank', 'operations supervisor', 'February 12, 2026', 'Flashbee Logistics', 'Location', 'Brampton (ON)', 'Salary\n\t\t\t\t\t\t$36.10 hourly', 'Job number:', '3507742', 'operations supervisor - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/jobsearch/jobposting/49102348?source=searchresults', '/reg/instructions', '#favourite-popup-49102348'],
    ['CareerBeacon', 'manager, computer applications', 'March 10, 2026', 'Scotiabank', 'Location', 'Toronto (ON)', 'Salary\n\t\t\t\t\t\t$43.75 to $103.37 hourly', 'Job number:', '2202049', 'manager, computer applications - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/reg/instructions', '/jobsearch/jobposting/49075943?source=searchresults', '#favourite-popup-49075943'],
    ['New', 'On site', 'Direct Apply', 'Posted on Job Bank', 'This job was posted directly by the employer on Job Bank.', 'Job Bank', 'data engineer', 'March 20, 2026', 'Clientserver Tech Systems', 'Location', 'Mississauga (ON)', 'Salary\n\t\t\t\t\t\t$51.00 hourly', 'Job number:', '3534559', 'data engineer - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/jobsearch/jobposting/49146098?source=searchresults', '/reg/instructions', '#favourite-popup-49146098'],
    ['New', 'Hybrid', 'CareerBeacon', 'manager, IT (information technology) implementation', 'March 17, 2026', 'Best Buy Canada', 'Location', 'Vancouver (BC)', 'Salary\n\t\t\t\t\t\t$40.00 to $92.00 hourly', 'Job number:', '2902606', 'manager, IT (information technology) implementation - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/jobsearch/jobposting/49121116?source=searchresults', '/reg/instructions', '#favourite-popup-49121116'],
    ['New', 'On site', 'Direct Apply', 'Posted on Job Bank', 'This job was posted directly by the employer on Job Bank.', 'Job Bank', 'office supervisor', 'March 18, 2026', 'Divinia Care Ltd.', 'Location', 'Edmonton (AB)', 'Salary\n\t\t\t\t\t\t$36.50 hourly', 'Job number:', '3532924', 'office supervisor - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/reg/instructions', '/jobsearch/jobposting/49134894?source=searchresults', '#favourite-popup-49134894'],
    ['On site', 'Direct Apply', 'Posted on Job Bank', 'This job was posted directly by the employer on Job Bank.', 'Job Bank', 'operations supervisor', 'February 24, 2026', 'Waves Coffee', 'Location', 'Edmonton (AB)', 'Salary\n\t\t\t\t\t\t$37.50 hourly', 'Job number:', '3367629', 'operations supervisor - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/reg/instructions', '/jobsearch/jobposting/48997797?source=searchresults', '#favourite-popup-48997797'],
    ['CareerBeacon', 'artificial intelligence (AI) consultant', 'March 11, 2026', 'Scotiabank', 'Location', 'Toronto (ON)', 'Salary\n\t\t\t\t\t\t$30.00 to $69.74 hourly', 'Job number:', '2193315', 'artificial intelligence (AI) consultant - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/jobsearch/jobposting/49090381?source=searchresults', '#favourite-popup-49090381', '/reg/instructions'],
    ['On site', 'Direct Apply', 'Posted on Job Bank', 'This job was posted directly by the employer on Job Bank.', 'Job Bank', 'operations supervisor', 'February 13, 2026', 'WHITE KNIGHT JANITORIAL SERVICE INC', 'Location', 'Surrey (BC)', 'Salary\n\t\t\t\t\t\t$36.60 hourly', 'Job number:', '3508296', 'operations supervisor - Save to favourites', 'Your favourites', 'To add a job posting to your favourites, you need a Job Bank account. Sign in or sign up now!', 'Sign in', 'Sign up for a Plus account', '/login', '/jobsearch/jobposting/49079659?source=searchresults', '/reg/instructions', '#favourite-popup-49079659'],
]
