"""
Canonical keyword lists for broad software and placement-role searches.

These lists are matched against job titles with SQL LIKE clauses, so they stay
focused on role names and role-shaped phrases rather than long descriptions.
"""

from __future__ import annotations


def _unique_keywords(*keywords: str) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []

    for keyword in keywords:
        cleaned = keyword.strip()
        if not cleaned:
            continue
        key = cleaned.casefold()
        if key in seen:
            continue
        seen.add(key)
        ordered.append(cleaned)

    return ordered


SOFTWARE_KEYWORDS = _unique_keywords(
    # General computing and IT roles
    "computer technician",
    "computer tech",
    "pc technician",
    "pc support technician",
    "personal computer technician",
    "computer support technician",
    "computer service technician",
    "computer repair technician",
    "computer operator",
    "computer engineer",
    "computer programmer",
    "computer programmer analyst",
    "computer programming analyst",
    "computer systems analyst",
    "computer systems manager",
    "manager computer systems",
    "computer systems development manager",
    "computer systems administrator",
    "computer systems specialist",
    "computer systems engineer",
    "information systems manager",
    "information systems analyst",
    "information technology business analyst",
    "it business analyst",
    "it analyst",
    "it specialist",
    "it support specialist",
    "technical support analyst",
    "technical support specialist",
    "help desk technician",
    "desktop support technician",
    "computer network technician",
    "computer networks technician",
    "computer networking technician",
    "computer networks manager",
    "network administrator",
    "application programmer",
    "application programming analyst",
    "application programming specialist",
    "systems programmer",
    "programmer, systems",
    "systems analyst",
    "systems administrator",
    # Broad software and application roles
    "software developer",
    "software engineer",
    "software programmer",
    "software architect",
    "application developer",
    "application engineer",
    "systems developer",
    "solutions developer",
    "technical developer",
    "programmer analyst",
    "developer analyst",
    "application analyst",
    "full stack developer",
    "full stack engineer",
    "full-stack developer",
    "full-stack engineer",
    "frontend developer",
    "frontend engineer",
    "front-end developer",
    "front-end engineer",
    "backend developer",
    "backend engineer",
    "back-end developer",
    "back-end engineer",
    "web developer",
    "website developer",
    "web application developer",
    "web software developer",
    "web engineer",
    "web programmer",
    "web integrator",
    "mobile developer",
    "mobile engineer",
    "app developer",
    "ios developer",
    "android developer",
    # Data and analytics
    "data analyst",
    "data engineer",
    "data scientist",
    "data architect",
    "data developer",
    "business data analyst",
    "analytics engineer",
    "reporting analyst",
    "business intelligence developer",
    "bi developer",
    "etl developer",
    "sql developer",
    "database developer",
    "database analyst",
    "database administrator",
    "database engineer",
    "data governance analyst",
    "data governance specialist",
    "data steward",
    "data quality analyst",
    "data quality engineer",
    "data platform engineer",
    "data infrastructure engineer",
    "data warehouse developer",
    "data lake developer",
    "data operations specialist",
    "data operations engineer",
    "machine learning engineer",
    "ml engineer",
    "ai engineer",
    "artificial intelligence engineer",
    "deep learning engineer",
    "computer vision engineer",
    "nlp engineer",
    # Cloud, DevOps, infra, security, QA
    "devops engineer",
    "site reliability engineer",
    "platform engineer",
    "infrastructure engineer",
    "cloud engineer",
    "cloud architect",
    "solutions architect",
    "systems architect",
    "kubernetes engineer",
    "terraform engineer",
    "azure developer",
    "security engineer",
    "cybersecurity engineer",
    "application security engineer",
    "penetration tester",
    "network engineer",
    "network developer",
    "network analyst",
    "network support technician",
    "network support specialist",
    "qa engineer",
    "quality assurance engineer",
    "test engineer",
    "test automation engineer",
    "automation engineer",
    # Embedded, integration, enterprise, and niche software roles
    "embedded developer",
    "embedded systems engineer",
    "firmware engineer",
    "integration engineer",
    "api developer",
    "game developer",
    "game engineer",
    "graphics programmer",
    "crm developer",
    "erp developer",
    "salesforce developer",
    "sap developer",
    # Tech-stack-specific roles
    "javascript developer",
    "typescript developer",
    "python developer",
    "java developer",
    "react developer",
    "angular developer",
    "go developer",
    "php developer",
    "swift developer",
    "ruby developer",
    "rust developer",
    "dotnet developer",
    "c# developer",
    "flask developer",
    "django developer",
    "fastapi developer",
    "node.js developer",
    "spring developer",
    # Entry and intermediate variants
    "junior developer",
    "junior engineer",
    "junior software developer",
    "junior software engineer",
    "junior web developer",
    "junior data analyst",
    "junior data engineer",
    "associate developer",
    "associate engineer",
    "associate software developer",
    "entry level developer",
    "entry level engineer",
    "entry level software developer",
    "entry level software engineer",
    "new grad developer",
    "new grad engineer",
    "graduate developer",
    "graduate engineer",
    "intermediate developer",
    "intermediate engineer",
    "intermediate software developer",
    "intermediate software engineer",
    "mid-level developer",
    "mid-level engineer",
)


PLACEMENT_KEYWORDS = _unique_keywords(
    "intern",
    "internship",
    "co-op",
    "co op",
    "coop",
    "student",
    "summer student",
    "work term",
    "placement",
    "developer intern",
    "software developer intern",
    "software engineer intern",
    "web developer intern",
    "data analyst intern",
    "data engineer intern",
    "data science intern",
    "machine learning intern",
    "qa intern",
    "devops intern",
)
